"""
bc_3d_visualizer.py - Interactive 3D Visualization of BC Research Results
=========================================================================
Creates Plotly interactive 3D visualizations and matplotlib static figures
showing the performance landscape: Speedup x Optimality x Error across
all tested graph topologies.

Reads results from results/phase1_results.json (generated by bc_research_main.py)
or falls back to results/probability_results.json and topology_summary.json.

Usage:
  python bc_3d_visualizer.py           # Generate all visualizations
  python bc_3d_visualizer.py --test    # Use existing data only
"""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import json, os, sys

try:
    import plotly.graph_objects as go
    import plotly.express as px
    from plotly.subplots import make_subplots
    HAS_PLOTLY = True
except ImportError:
    HAS_PLOTLY = False

RESULTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'results')
TOPO_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'topology_analysis')


def load_phase1_results():
    """Load Phase 1 benchmark results from JSON."""
    path = os.path.join(RESULTS_DIR, 'phase1_results.json')
    if os.path.exists(path):
        with open(path) as f:
            raw = json.load(f)
        for r in raw:
            if 'smart_optimality' in r and 'optimality' not in r:
                r['optimality'] = r['smart_optimality']
            if 'optimality' not in r:
                r['optimality'] = 100.0
            if 'error_pct' not in r:
                r['error_pct'] = 100 - r['optimality']
            if 'bf_reduction' not in r:
                r['bf_reduction'] = 0
            if 'smart_reduction' not in r:
                r['smart_reduction'] = 0
        return raw

    path2 = os.path.join(RESULTS_DIR, 'probability_results.json')
    if os.path.exists(path2):
        with open(path2) as f:
            raw = json.load(f)
        results = []
        for r in raw:
            results.append({
                'name': r['name'],
                'topology': r['name'].split('_')[0],
                'nodes': r['nodes'],
                'edges': r.get('edges', 0),
                'bf_time_ms': r['bf']['time'],
                'smart_time_ms': r['prob']['time'],
                'speedup': r['prob']['speedup'],
                'optimality': r['prob']['opt'],
                'error_pct': 100 - r['prob']['opt'],
                'bf_edge': [],
                'smart_edge': [],
            })
        return results
    return []


def load_topology_summary():
    """Load topology-level summary from existing analysis."""
    path = os.path.join(RESULTS_DIR, 'topology_summary.json')
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {}


def create_plotly_3d(results):
    """Create interactive 3D Plotly visualization."""
    if not HAS_PLOTLY or not results:
        print("  Plotly not available or no data, skipping interactive 3D")
        return

    topos = list(set(r.get('topology', r['name'][:3]) for r in results))
    color_map = px.colors.qualitative.Set3

    fig = make_subplots(
        rows=2, cols=2,
        specs=[
            [{'type': 'scatter3d'}, {'type': 'scatter3d'}],
            [{'type': 'scatter'}, {'type': 'scatter'}]
        ],
        subplot_titles=[
            '3D: Speedup × Optimality × Error',
            '3D: Nodes × BF Time × Smart Time',
            'Speedup vs Optimality (2D)',
            'Error % by Graph'
        ]
    )

    for i, topo in enumerate(topos):
        tr = [r for r in results if r.get('topology', r['name'][:3]) == topo]
        col = color_map[i % len(color_map)]

        fig.add_trace(go.Scatter3d(
            x=[r['speedup'] for r in tr],
            y=[r['optimality'] for r in tr],
            z=[r['error_pct'] for r in tr],
            mode='markers+text',
            marker=dict(size=6, color=col, opacity=0.7),
            text=[r['name'][:12] for r in tr],
            textposition='top center',
            textfont=dict(size=7),
            name=topo,
            legendgroup=topo,
        ), row=1, col=1)

        fig.add_trace(go.Scatter3d(
            x=[r['nodes'] for r in tr],
            y=[r['bf_time_ms'] for r in tr],
            z=[r['smart_time_ms'] for r in tr],
            mode='markers',
            marker=dict(size=5, color=col, opacity=0.6),
            name=topo,
            legendgroup=topo,
            showlegend=False,
        ), row=1, col=2)

        fig.add_trace(go.Scatter(
            x=[r['speedup'] for r in tr],
            y=[r['optimality'] for r in tr],
            mode='markers',
            marker=dict(size=8, color=col, opacity=0.7),
            name=topo,
            legendgroup=topo,
            showlegend=False,
        ), row=2, col=1)

        fig.add_trace(go.Bar(
            x=[r['name'][:10] for r in tr],
            y=[r['error_pct'] for r in tr],
            marker_color=col,
            name=topo,
            legendgroup=topo,
            showlegend=False,
        ), row=2, col=2)

    fig.update_layout(
        title=dict(text='BC Minimization: BF vs Smart Algorithm — 3D Performance Analysis',
                   font=dict(size=18)),
        height=1000,
        showlegend=True,
        template='plotly_white',
    )

    fig.update_scenes(
        xaxis_title='Speedup', yaxis_title='Optimality %', zaxis_title='Error %',
        row=1, col=1)
    fig.update_scenes(
        xaxis_title='Nodes', yaxis_title='BF Time (ms)', zaxis_title='Smart Time (ms)',
        row=1, col=2)

    path = os.path.join(RESULTS_DIR, '3d_interactive.html')
    fig.write_html(path)
    print(f"  Saved interactive 3D: {path}")


def create_matplotlib_3d(results):
    """Create static 3D matplotlib figures."""
    if not results:
        print("  No results to visualize")
        return

    fig = plt.figure(figsize=(20, 16))

    topos = list(set(r.get('topology', r['name'][:3]) for r in results))
    cmap = plt.cm.Set3(np.linspace(0, 1, max(len(topos), 1)))
    topo_colors = {t: cmap[i] for i, t in enumerate(topos)}

    ax1 = fig.add_subplot(221, projection='3d')
    for t in topos:
        tr = [r for r in results if r.get('topology', r['name'][:3]) == t]
        ax1.scatter(
            [r['speedup'] for r in tr],
            [r['optimality'] for r in tr],
            [r['error_pct'] for r in tr],
            s=50, alpha=0.7, label=t[:12], color=topo_colors[t])
    ax1.set_xlabel('Speedup (x)')
    ax1.set_ylabel('Optimality (%)')
    ax1.set_zlabel('Error (%)')
    ax1.set_title('3D: Speedup × Optimality × Error\n(each dot = one graph instance)',
                   fontweight='bold')
    ax1.legend(fontsize=5, ncol=2)

    ax2 = fig.add_subplot(222, projection='3d')
    for t in topos:
        tr = [r for r in results if r.get('topology', r['name'][:3]) == t]
        ax2.scatter(
            [r['nodes'] for r in tr],
            [r['bf_time_ms'] for r in tr],
            [r['smart_time_ms'] for r in tr],
            s=50, alpha=0.7, label=t[:12], color=topo_colors[t])
    ax2.set_xlabel('Nodes')
    ax2.set_ylabel('BF Time (ms)')
    ax2.set_zlabel('Smart Time (ms)')
    ax2.set_title('3D: Graph Size × BF Time × Smart Time\n(smart always bottom-right)',
                   fontweight='bold')
    ax2.legend(fontsize=5, ncol=2)

    ax3 = fig.add_subplot(223)
    topo_means = {}
    for t in topos:
        tr = [r for r in results if r.get('topology', r['name'][:3]) == t]
        topo_means[t] = {
            'spd': np.mean([r['speedup'] for r in tr]),
            'opt': np.mean([r['optimality'] for r in tr]),
            'err': np.mean([r['error_pct'] for r in tr]),
            'n': np.mean([r['nodes'] for r in tr]),
        }
    for t, m in topo_means.items():
        ax3.scatter(m['spd'], m['opt'], s=m['n'] * 5, alpha=0.7,
                    color=topo_colors[t], edgecolors='black', linewidth=1)
        ax3.annotate(t[:10], (m['spd'], m['opt']), fontsize=7,
                     ha='center', va='bottom', fontweight='bold')
    ax3.axhline(100, color='gray', ls='--', lw=1)
    ax3.set_xlabel('Mean Speedup')
    ax3.set_ylabel('Mean Optimality (%)')
    ax3.set_title('Topology Summary: Speedup vs Optimality\n(bubble size = avg nodes)',
                   fontweight='bold')
    ax3.grid(True, alpha=0.3)

    ax4 = fig.add_subplot(224)
    sorted_topos = sorted(topo_means.keys(), key=lambda t: topo_means[t]['err'])
    y_pos = range(len(sorted_topos))
    errs = [topo_means[t]['err'] for t in sorted_topos]
    colors_e = ['#2ecc71' if e < 5 else '#f39c12' if e < 40 else '#e74c3c' for e in errs]
    ax4.barh(list(y_pos), errs, color=colors_e, alpha=0.8, edgecolor='white')
    ax4.set_yticks(list(y_pos))
    ax4.set_yticklabels([t[:12] for t in sorted_topos], fontsize=8)
    ax4.set_xlabel('Average Error (%)')
    ax4.set_title('Error by Topology\n(Green <5% | Orange 5-40% | Red >40%)',
                   fontweight='bold')
    for i, (e, t) in enumerate(zip(errs, sorted_topos)):
        ax4.text(e + 0.5, i, f'{e:.1f}%', va='center', fontsize=7)

    fig.suptitle('BC Minimization: 3D Performance Analysis\nBrute Force vs Smart Algorithm',
                 fontsize=16, fontweight='bold', y=0.98)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    path = os.path.join(RESULTS_DIR, 'phase1_3d_scatter.png')
    plt.savefig(path, bbox_inches='tight')
    plt.close()
    print(f"  Saved static 3D: {path}")


def create_edge_comparison_figure(results):
    """Show which edges BF vs Smart selected per graph type."""
    results = [r for r in results if 'bf_reduction' in r and 'smart_reduction' in r]
    if not results:
        return

    topos = list(set(r.get('topology', 'unknown') for r in results))
    fig, axes = plt.subplots(2, 5, figsize=(22, 8))
    axes = axes.flatten()

    for i, topo in enumerate(topos[:10]):
        if i >= 10:
            break
        ax = axes[i]
        tr = [r for r in results if r.get('topology') == topo][:5]
        names = [r['name'][:10] for r in tr]
        x = np.arange(len(tr))
        bf_reds = [r.get('bf_reduction', 0) * 1000 for r in tr]
        sm_reds = [r.get('smart_reduction', 0) * 1000 for r in tr]
        w = 0.35
        ax.bar(x - w / 2, bf_reds, w, label='BF', color='#D85A30', alpha=0.8)
        ax.bar(x + w / 2, sm_reds, w, label='Smart', color='#1D9E75', alpha=0.8)
        for j, r in enumerate(tr):
            if r.get('same_edge'):
                ax.text(j, max(bf_reds[j], sm_reds[j]), '✓',
                        ha='center', fontsize=10, color='green')
        ax.set_title(topo[:15], fontsize=8, fontweight='bold')
        ax.set_xticks(x)
        ax.set_xticklabels(names, rotation=45, fontsize=5)
        if i == 0:
            ax.legend(fontsize=6)
        ax.set_ylabel('Reduction (×10³)', fontsize=6)

    for j in range(len(topos), 10):
        axes[j].axis('off')

    fig.suptitle('Edge Addition Comparison: BF vs Smart per Topology\n(✓ = same edge found)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.93])
    path = os.path.join(RESULTS_DIR, 'edge_comparison.png')
    plt.savefig(path, bbox_inches='tight')
    plt.close()
    print(f"  Saved edge comparison: {path}")


if __name__ == '__main__':
    print("=" * 60)
    print("  BC Minimization: 3D Visualization Generator")
    print("=" * 60)

    results = load_phase1_results()
    if not results:
        print("  No phase1 results found. Run bc_research_main.py first.")
        sys.exit(1)

    print(f"  Loaded {len(results)} graph results")
    create_matplotlib_3d(results)
    create_plotly_3d(results)
    create_edge_comparison_figure(results)
    print("\n  Done!")
